name: media_kit_video
description: Native implementation for video playback in package:media_kit.

publish_to: 'none'
homepage: https://github.com/wavestore-global/media-kit.git
repository: https://github.com/wavestore-global/media-kit.git
version: 1.2.4
topics:
  - video
  - video-player
  - audio
  - audio-player
  - cross-platform

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit:
    git:
      url: git@github.com:wavestore-global/media-kit.git
      ref: main
      path: media_kit

  synchronized: ^3.1.0
  wakelock_plus: ^1.1.1
  screen_brightness: ^0.2.2
  volume_controller: ^2.0.7
  universal_platform: ^1.0.0+1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

# NOTE: Remove before publishing to pub.dev
dependency_overrides:
  media_kit:
    path: ../media_kit

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MediaKitVideoPluginCApi
      linux:
        pluginClass: MediaKitVideoPlugin
      macos:
        pluginClass: MediaKitVideoPlugin
      ios:
        pluginClass: MediaKitVideoPlugin
      android:
        package: com.alexmercerind.media_kit_video
        pluginClass: MediaKitVideoPlugin
      web:
